/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import {MeshReflectorMaterial} from '@react-three/drei';
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/model/scene.glb");
  const beam_material=new THREE.MeshStandardMaterial({side:THREE.BackSide,color:"#101010",metalness:0.5,roughness:0.8})
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 18]}>
        <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_1.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_2.geometry}
            material={beam_material}
          />
        </group>
        <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_3.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_4.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_5.geometry}
            material={beam_material}
          />
        </group>
        <group position={[0, -10, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_6.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_7.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_8.geometry}
            material={beam_material}
          />
        </group>
        <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_9.geometry}
    material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_10.geometry}
        material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_11.geometry}
        material={beam_material}
          />
        </group>
        <group position={[0, 0, 3]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_12.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_13.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_14.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_15.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_16.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_17.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_18.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_19.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_20.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_21.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_22.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_23.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 6]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_24.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_25.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_26.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_27.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_28.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_29.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_30.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_31.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_32.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_33.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_34.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_35.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 9]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_36.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_37.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_38.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_39.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_40.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_41.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_42.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_43.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_44.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_45.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_46.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_47.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 12]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_48.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_49.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_50.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_51.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_52.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_53.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_54.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_55.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_56.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_57.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_58.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_59.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 15]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_60.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_61.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_62.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_63.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_64.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_65.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_66.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_67.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_68.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_69.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_70.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_71.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 18]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_72.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_73.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_74.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_75.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_76.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_77.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_78.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_79.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_80.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_81.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_82.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_83.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 21]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_84.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_85.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_86.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_87.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_88.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_89.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_90.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_91.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_92.geometry}
            material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_93.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_94.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_95.geometry}
            material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 24]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_96.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_97.geometry}
            material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_98.geometry}
            material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_99.geometry}
            material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_100.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_101.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_102.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_103.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_104.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_105.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_106.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_107.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 27]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_108.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_109.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_110.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_111.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_112.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_113.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_114.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_115.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_116.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_117.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_118.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_119.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 30]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_120.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_121.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_122.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_123.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_124.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_125.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_126.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_127.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_128.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_129.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_130.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_131.geometry}
              material={beam_material}
            />
          </group>
        </group>
      </group>
      <group position={[0, 0, -15]}>
        <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_132.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_133.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_134.geometry}
            material={beam_material}
          />
        </group>
        <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_135.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_136.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_137.geometry}
            material={beam_material}
          />
        </group>
        <group position={[0, -10, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_138.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_139.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_140.geometry}
            material={beam_material}
          />
        </group>
        <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_141.geometry}
            material={beam_material}
            position={[0, 0.35, -0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_142.geometry}
            material={beam_material}
            position={[0, 0.35, 0.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_143.geometry}
            material={beam_material}
          />
        </group>
        <group position={[0, 0, 3]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_144.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_145.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_146.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_147.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_148.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_149.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_150.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_151.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_152.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_153.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_154.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_155.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 6]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_156.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_157.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_158.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_159.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_160.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_161.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_162.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_163.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_164.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_165.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_166.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_167.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 9]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_168.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_169.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_170.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_171.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_172.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_173.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_174.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_175.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_176.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_177.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_178.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_179.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 12]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_180.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_181.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_182.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_183.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_184.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_185.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_186.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_187.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_188.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_189.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_190.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_191.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 15]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_192.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_193.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_194.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_195.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_196.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_197.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_198.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_199.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_200.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_201.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_202.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_203.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 18]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_204.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_205.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_206.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_207.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_208.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_209.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_210.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_211.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_212.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_213.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_214.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_215.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 21]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_216.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_217.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_218.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_219.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_220.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_221.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_222.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_223.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_224.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_225.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_226.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_227.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 24]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_228.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_229.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_230.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_231.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_232.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_233.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_234.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_235.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_236.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_237.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_238.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_239.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 27]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_240.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_241.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_242.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_243.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_244.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_245.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_246.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_247.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_248.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_249.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_250.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_251.geometry}
              material={beam_material}
            />
          </group>
        </group>
        <group position={[0, 0, 30]}>
          <group position={[10, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_252.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_253.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_254.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, 10, 0]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_255.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_256.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_257.geometry}
              material={beam_material}
            />
          </group>
          <group position={[0, -10, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_258.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_259.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_260.geometry}
              material={beam_material}
            />
          </group>
          <group position={[-10, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_261.geometry}
              material={beam_material}
              position={[0, 0.35, -0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_262.geometry}
              material={beam_material}
              position={[0, 0.35, 0.45]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_263.geometry}
              material={beam_material}
            />
          </group>
        </group>
      </group>

      <rectAreaLight
          width={10}
          height={10}
          color={"#ffffff"}
          intensity={10}
          position={[0, 0, -15]}
          rotation={[0,Math.PI,0]}
          penumbra={1}
          castShadow
        />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        rotation={[Math.PI / 2, Math.PI / 4, 0]}
      >
          <meshStandardMaterial side={THREE.BackSide} roughness={1} metalness={0.5} color="#101010" ></meshStandardMaterial>
      </mesh>
        <pointLight position={[0,0,60]} intensity={2}></pointLight>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        position={[0, -6.08, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
          <MeshReflectorMaterial
            blur={[300, 100]}
            resolution={2048}
            mixBlur={1}
            mixStrength={40}
            roughness={1}
            depthScale={1.2}
            minDepthThreshold={0.4}
            maxDepthThreshold={1.4}
            color="#101010"
            metalness={0.5}
          />
      </mesh>
    </group>

  );
}

useGLTF.preload("/scene.glb");